### ISSUE TITLE
POJO deserialization fails

### ISSUE THREAD

**Issue by Iamnotagenius** [falkreon/Jankson#77]
I get a DeseralizationException when deserializing POJO which has been serialized by Jankson. This is what I get:
```
 blue.endless.jankson.api.DeserializationException: There was a problem unpacking field progressChances of class net.backupcup.mcde.Con
fig
        at blue.endless.jankson.impl.POJODeserializer.unpackField(POJODeserializer.java:110) ~[jankson-1.2.3.jar:?]
        at blue.endless.jankson.impl.POJODeserializer.unpackObject(POJODeserializer.java:74) ~[jankson-1.2.3.jar:?]
        at blue.endless.jankson.impl.MarshallerImpl.marshall(MarshallerImpl.java:284) ~[jankson-1.2.3.jar:?]
        at blue.endless.jankson.impl.MarshallerImpl.marshallCarefully(MarshallerImpl.java:191) ~[jankson-1.2.3.jar:?]
        at blue.endless.jankson.Jankson.fromJsonCarefully(Jankson.java:309) ~[jankson-1.2.3.jar:?]
...
Caused by: java.lang.UnsupportedOperationException
        at java.util.ImmutableCollections.uoe(ImmutableCollections.java:142) ~[?:?]
        at java.util.ImmutableCollections$AbstractImmutableMap.clear(ImmutableCollections.java:1067) ~[?:?]
        at blue.endless.jankson.impl.POJODeserializer.unpackMap(POJODeserializer.java:221) ~[jankson-1.2.3.jar:?]
        at blue.endless.jankson.impl.POJODeserializer.unpackFieldData(POJODeserializer.java:196) ~[jankson-1.2.3.jar:?]
        at blue.endless.jankson.impl.POJODeserializer.unpackField(POJODeserializer.java:108) ~[jankson-1.2.3.jar:?]
```

This only happens in 1.2.3 (in 1.2.2 it doesn't cause an exception)
Definition of a field in question:
```java
private Map<Identifier, Map<Slots, Float>> progressChances = Map.ofEntries(
    <default entries>
);
```
`Identifier` is a minecraft's class (I registered custom (de)serializer for it:
```java
    private static final Jankson JANKSON = Jankson.builder()
        .registerSerializer(Identifier.class, (id, marshaller) -> marshaller.serialize(id.toString()))
        .registerDeserializer(String.class, Identifier.class, (str, marshaller) -> Identifier.tryParse(str))
        .build();
```
And `Slots` is a simple enum.

**Comment by falkreon** [comment]
The problem is the value of the destination field. `Map.ofEntries()` creates an immutable map. When Jankson encounters an initialized field, it attempts to unpack to it. In 1.2.2 this would silently fail; in 1.2.3 it correctly crashes.

The quickest, easiest fix is to switch from
```java
private Map<Identifier, Map<Slots, Float>> progressChances = Map.ofEntries(
    <default entries>
);
```

to

```java
private Map<Identifier, Map<Slots, Float>> progressChances = new HashMap(Map.ofEntries(
    <default entries>
));
```

**Comment by Iamnotagenius** [comment]
probably would've been better if jankson checked if map is immutable and if it is, it will create a new map

**Comment by falkreon** [comment]
I feel like it's bad practice to replace an immutable map with a mutable one, but it's something I'm considering for future versions *provided that the field is a mutable type*
