### ISSUE TITLE
An exception occurred with `jankson. load ("[]")`

### ISSUE THREAD

**Issue by rongrong1000** [falkreon/Jankson#89]

**Comment by Fox2Code** [comment]
@rongrong1000 which version of Jankson? Is it Jankson 1 or Jankson 2?

**Comment by rongrong1000** [comment]
> @rongrong1000 which version of Jankson? Is it Jankson 1 or Jankson 2?

version 1.2.3
``` java
@SneakyThrows
    public static void main(String[] args) {
        JsonObject load = Jankson.builder().build().load("[]");
        System.out.println(load);
    }
```

```
Exception in thread "main" blue.endless.jankson.api.SyntaxError: Found character '[' instead of '{' while looking for the start of an object
	at blue.endless.jankson.impl.ObjectParserContext.consume(ObjectParserContext.java:75)
	at blue.endless.jankson.Jankson.processCodePoint(Jankson.java:339)
	at blue.endless.jankson.Jankson.load(Jankson.java:196)
	at blue.endless.jankson.Jankson.load(Jankson.java:73)
```
